name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Fetch and merge remote changes
        run: git fetch origin && git merge origin/main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://asadnhasan:$HF_TOKEN@huggingface.co/spaces/asadnhasan/PDF-Chat-using-AI main:main
